version: '3'

volumes:
  mysql57_data:
    external: true

services:
  database:
    image: "mysql:5.7.26"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: chrysalis
    ports:
      - "3305:3306"
    volumes:
      - mysql57_data:/var/lib/mysql